package com.redhat.summit2015.ceplab
 
import java.math.BigDecimal;

import com.redhat.summit2015.ceplab.model.Account;
import com.redhat.summit2015.ceplab.model.AccountStatus;

/*
    When there is an Account with a $0 dollar balance terminate the Account
*/
rule "Zero Balance"
    when
        $account : Account( balance <= BigDecimal.ZERO && status != AccountStatus.TERMINATED )
    then
        System.out.println("terminating account " + $account);
        $account.setStatus( AccountStatus.TERMINATED );
        update( $account );
end

